<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<groupId>com.zoostarinc.employee</groupId>
	<artifactId>employee-parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<properties>
		<zoostar.boot.version>3.4.0</zoostar.boot.version>
	</properties>
	<parent>
		<groupId>net.zoostar.boot</groupId>
		<artifactId>zoostar-boot-starter-parent</artifactId>
		<version>3.4.0</version>
		<relativePath />
	</parent>
	<modules>
		<module>employee-web</module>
		<module>employee-api</module>
		<module>employee-spi</module>
		<module>employee-core</module>
	</modules>
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>net.zoostar.common</groupId>
				<artifactId>zoostar-common</artifactId>
				<version>${zoostar.boot.version}</version>
			</dependency>
			<dependency>
				<groupId>com.zoostarinc.employee</groupId>
				<artifactId>employee-core</artifactId>
				<version>${project.version}</version>
			</dependency>
			<dependency>
				<groupId>com.zoostarinc.employee</groupId>
				<artifactId>employee-spi</artifactId>
				<version>${project.version}</version>
			</dependency>
		</dependencies>
	</dependencyManagement>
	<dependencies>
		<dependency>
			<groupId>net.zoostar.common</groupId>
			<artifactId>zoostar-common</artifactId>
		</dependency>
	</dependencies>
</project>