DROP TABLE IF EXISTS EMPLOYEE CASCADE;

CREATE TABLE EMPLOYEE (
    ID UUID PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(30),
    LAST_NAME VARCHAR(30),
    CONSTRAINT EMAIL_UNQ 
    UNIQUE (EMAIL)
);
