DROP TABLE IF EXISTS EMPLOYEE CASCADE;

CREATE TABLE EMPLOYEE (
    ID VARCHAR(100) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CONSTRAINT USERNAME_UNQ 
    UNIQUE (USERNAME)
);
