DROP TABLE IF EXISTS EMPLOYEE CASCADE;

CREATE TABLE EMPLOYEE (
    ID VARCHAR(100) PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    CONSTRAINT EMAIL_UNQ 
    UNIQUE (EMAIL)
);
